name: Build and Push Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: AWS

    steps:

      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build and push ADMIN
      - name: Build and push admin
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: final-project
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG ./admin
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # 5. Build and push FRONTEND
      - name: Build and push frontend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG ./frontend
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # 6. Build and push BACKEND
      - name: Build and push backend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG ./backend
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
